import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ระบบจัดการสินค้าในร้าน",
  description: "Generated by create next app",
};

/** กำหนดโครง HTML หลัก ฟอนต์ และ Toast provider ให้ทุกหน้าในแอป */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: '#1e3a5f',
              border: '1px solid #2563eb',
              color: '#fff'
            }
          }}
        />
        {children}</body>
    </html>
  );
}
